services:
  backend:
    build:
      context: ./Backend
      platforms:
        - linux/amd64
        # - linux/arm64
    ports:
      - "5000:5000"
    env_file:
      - .env


  frontend:
    build: 
      context: .
      platforms:
        - linux/amd64
        # - linux/arm64
      args:
        VITE_BACKEND_URL: http://localhost:5000
    env_file:
      - .env
    ports:
      - "5173:5173"
    # depends_on:
    #   - backend
